name: Build ESP32 Firmware

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Install ESP32 platform
        run: |
          arduino-cli core update-index --additional-urls https://espressif.github.io/arduino-esp32/package_esp32_index.json
          arduino-cli core install esp32:esp32 --additional-urls https://espressif.github.io/arduino-esp32/package_esp32_index.json

      - name: Install WiFiManager
        run: |
          arduino-cli lib update-index
          arduino-cli lib install "WiFiManager"

      - name: Compile firmware
        run: |
          mkdir -p build
          arduino-cli compile --fqbn esp32:esp32:esp32 --output-dir ./build sketch

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: ESP32-Firmware
          path: build/*.bin
